# Generated by Django 5.2.14 on 2026-08-10 18:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código da Conta Contábil')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome / Descrição da Conta')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada')),
            ],
            options={
                'verbose_name': 'Conta Contábil',
                'verbose_name_plural': 'Contas Contábeis',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CicloInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Inventário')),
                ('termo_numero', models.CharField(help_text='Ex: 2BAEP - 001/40/2026', max_length=100, verbose_name='Número do Termo')),
                ('ano', models.PositiveIntegerField(default=2026, verbose_name='Ano de Exercício')),
                ('semestre', models.PositiveSmallIntegerField(choices=[(1, '1º Semestre'), (2, '2º Semestre')], default=1, verbose_name='Semestre')),
                ('data_referencia', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Inventário')),
                ('detentor_executivo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Detentor Executivo (Responsável)')),
                ('opm_codigos', models.CharField(blank=True, default='606020000, 606028000, 606028400', max_length=150, null=True, verbose_name='Códigos OPM')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_ANDAMENTO', 'Em Andamento / Conferência'), ('CONCLUIDO', 'Concluído'), ('HOMOLOGADO', 'Homologado')], default='EM_ANDAMENTO', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações / Notas do Inventário')),
                ('arquivo_origem', models.FileField(blank=True, null=True, upload_to='inventarios/planilhas/', verbose_name='Planilha de Origem (.xlsx)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ciclo de Inventário Semestral',
                'verbose_name_plural': 'Ciclos de Inventário Semestral',
                'ordering': ['-ano', '-semestre', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao_subunidade', models.CharField(help_text='Ex: 606028400 - P/4', max_length=150, verbose_name='Seção / Subunidade')),
                ('patrimonio', models.CharField(db_index=True, max_length=100, verbose_name='Patrimônio / Tombo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série')),
                ('tipo_material', models.CharField(max_length=200, verbose_name='Tipo de Material / Descrição')),
                ('situacao_material', models.CharField(default='EM USO', max_length=150, verbose_name='Situação do Material')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Contábil (R$)')),
                ('conferido', models.BooleanField(default=False, verbose_name='Conferido Fisiocamente')),
                ('situacao_fisica_conferida', models.CharField(choices=[('CONFORME', 'Conforme / Em Uso'), ('AVARIADO', 'Avariado / Danificado'), ('NAO_LOCALIZADO', 'Não Localizado / Divergente'), ('EM_EXCLUSAO', 'Processo de Exclusão')], default='CONFORME', max_length=20, verbose_name='Situação Física Conferida')),
                ('data_conferencia', models.DateTimeField(blank=True, null=True, verbose_name='Data da Conferência')),
                ('observacoes_conferencia', models.TextField(blank=True, null=True, verbose_name='Observações da Conferência')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='inventario.cicloinventario', verbose_name='Ciclo de Inventário')),
                ('conferido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_inventario_conferidos', to=settings.AUTH_USER_MODEL, verbose_name='Conferido Por')),
                ('conta_contabil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='inventario.contacontabil', verbose_name='Conta Contábil')),
            ],
            options={
                'verbose_name': 'Item do Inventário',
                'verbose_name_plural': 'Itens do Inventário',
                'ordering': ['conta_contabil__codigo', 'secao_subunidade', 'patrimonio'],
            },
        ),
    ]
