# Generated by Django 5.2.4 on 2026-02-18 18:37

import uuid
from django.db import migrations, models


def _populate_qr_tokens(apps, schema_editor):
    Produto = apps.get_model('estoque', 'Produto')
    for produto in Produto.objects.filter(qr_code_token__isnull=True):
        produto.qr_code_token = uuid.uuid4()
        produto.save(update_fields=['qr_code_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='qr_code_imagem',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='produtos/qrcodes/', verbose_name='QR Code'),
        ),
        migrations.AddField(
            model_name='produto',
            name='qr_code_token',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='Token QR Code'),
        ),
        migrations.RunPython(
            code=_populate_qr_tokens,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='produto',
            name='qr_code_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token QR Code'),
        ),
    ]
