# Generated by Django 5.2.4 on 2026-02-25 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_seed_unidades_medida_e_categoria_padrao'),
        ('policiais', '0002_alter_policial_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='documento_quem_retirou',
            field=models.CharField(blank=True, help_text='Documento de identificação de quem retirou o material', max_length=50, null=True, verbose_name='Documento Quem Retirou'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='responsavel_autorizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizacoes_movimentacoes', to='policiais.policial', verbose_name='Responsável pela Autorização'),
        ),
        migrations.AddField(
            model_name='produto',
            name='conta_contabil',
            field=models.CharField(blank=True, help_text='Código da conta contábil do material', max_length=50, null=True, verbose_name='Conta Contábil'),
        ),
        migrations.AddField(
            model_name='produto',
            name='localizacao_fisica',
            field=models.CharField(blank=True, help_text='Ex: Armário 5, Prateleira A, Ala 2', max_length=200, null=True, verbose_name='Localização Física'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número do Empenho'),
        ),
    ]
