# Generated by Django 5.2.12 on 2026-03-31 17:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_movimentacaoestoque_documento_quem_retirou_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conta Patrimonial',
                'verbose_name_plural': 'Contas Patrimoniais',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cor',
                'verbose_name_plural': 'Cores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LocalizacaoFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Localização Física',
                'verbose_name_plural': 'Localizações Físicas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MilitarRequisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re', models.CharField(max_length=20, unique=True, verbose_name='RE')),
                ('qra', models.CharField(max_length=100, verbose_name='QRA (Nome de Guerra)')),
                ('nome_completo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Completo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Militar Requisitante',
                'verbose_name_plural': 'Militares Requisitantes',
                'ordering': ['re'],
            },
        ),
        migrations.CreateModel(
            name='OrgaoRequisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('sigla', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sigla')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Órgão Requisitante',
                'verbose_name_plural': 'Órgãos Requisitantes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeFornecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('padrao', models.BooleanField(default=False, help_text='Marca esta unidade de fornecimento como padrão do sistema', verbose_name='Padrão (Unidade)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unidade de Fornecimento',
                'verbose_name_plural': 'Unidades de Fornecimento',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ['data_cadastro'], 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['codigo', 'nome'], 'verbose_name': 'Material de Consumo', 'verbose_name_plural': 'Materiais de Consumo'},
        ),
        migrations.RemoveIndex(
            model_name='movimentacaoestoque',
            name='estoque_mov_produto_fe5614_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimentacaoestoque',
            name='estoque_mov_tipo_mo_840f50_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimentacaoestoque',
            name='estoque_mov_data_ho_8ba572_idx',
        ),
        migrations.RemoveIndex(
            model_name='produto',
            name='estoque_pro_tipo_pr_8de1e8_idx',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='destino_origem',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='documento_quem_retirou',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='responsavel_autorizacao',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='solicitante',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='conta_contabil',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tipo_produto',
        ),
        migrations.AddField(
            model_name='iteminventario',
            name='justificativa_divergencia',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa da Divergência'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='data_movimentacao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Movimentação'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='nota_fiscal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='subtipo',
            field=models.CharField(choices=[('COMPRA_NOVA', 'Compra Nova'), ('DEVOLUCAO_ENTRADA', 'Devolução'), ('REQUISICAO', 'Requisição'), ('DESCARTE', 'Descarte'), ('TRANSFERENCIA', 'Transferência'), ('AJUSTE_INVENTARIO', 'Ajuste de Inventário'), ('OUTROS', 'Outros')], default='OUTROS', help_text='Compra Nova / Devolução / Requisição / Descarte', max_length=30, verbose_name='Subtipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='unidade_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.unidademedida', verbose_name='Unidade de Medida do Item'),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_cat_mat',
            field=models.CharField(blank=True, help_text='Conforme Termo de Referência', max_length=50, null=True, verbose_name='Código CAT MAT'),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_siafisico',
            field=models.CharField(blank=True, help_text='Conforme Termo de Referência', max_length=50, null=True, verbose_name='Código SIAFÍSICO'),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_cotacao',
            field=models.DateField(blank=True, help_text='Alerta automático após 180 dias', null=True, verbose_name='Data da Cotação'),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_inicio_projeto',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início do Projeto de Aquisição'),
        ),
        migrations.AddField(
            model_name='produto',
            name='historico_subcategoria',
            field=models.TextField(blank=True, help_text='Registrar atualizações da subcategoria', null=True, verbose_name='Histórico / Observações da Subcategoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_medio',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Preço médio de aquisição', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço Médio'),
        ),
        migrations.AddField(
            model_name='produto',
            name='processo_sei',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Processo SEI nº'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tempo_reposicao',
            field=models.PositiveIntegerField(default=0, help_text='Em dias. Calculado ou informado manualmente.', verbose_name='Tempo de Reposição (dias)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='termo_referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Termo de Referência nº'),
        ),
        migrations.AlterField(
            model_name='ajusteestoque',
            name='data_aprovacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ajusteestoque',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ajusteestoque',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações / Justificativa'),
        ),
        migrations.AlterField(
            model_name='ajusteestoque',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='ajusteestoque',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Valor Unitário'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='tipo_inventario',
            field=models.CharField(choices=[('COMPLETO', 'Completo'), ('PARCIAL', 'Parcial'), ('ROTATIVO', 'Rotativo'), ('SORTEIO', 'Por Sorteio')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='status_contagem',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONTADO', 'Contado'), ('AJUSTADO', 'Ajustado')], default='PENDENTE', max_length=20, verbose_name='Status Contagem'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora do Registro'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to='estoque.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_estoque', to='estoque.produto', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste de Estoque')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Valor Unitário'),
        ),
        migrations.AlterField(
            model_name='numeroserie',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='numeroserie',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(help_text='Código único do material. Ex: MAT-001', max_length=50, unique=True, verbose_name='Código Único'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Preparado para futura leitura por scanner', max_length=100, null=True, unique=True, verbose_name='Código de Barras / Empenho'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, help_text='Conforme Termo de Referência', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_atual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cache — use saldo_calculado para operações', max_digits=10, verbose_name='Estoque Atual (cache)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_maximo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Estoque Máximo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Estoque Mínimo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(help_text='Ex: Caneta Azul, Papel Sulfite A4', max_length=200, verbose_name='Subcategoria (Nome do Material)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.unidademedida', verbose_name='Unidade de Medida do Item'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Valor Unitário'),
        ),
        migrations.AlterField(
            model_name='unidademedida',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='unidademedida',
            name='sigla',
            field=models.CharField(max_length=20, unique=True, verbose_name='Sigla'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='conta_patrimonial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.contapatrimonial', verbose_name='Conta Patrimonial'),
        ),
        migrations.AddField(
            model_name='produto',
            name='conta_patrimonial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.contapatrimonial', verbose_name='Conta Patrimonial'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='cor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.cor', verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='localizacao_fisica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.localizacaofisica', verbose_name='Localização Física'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='localizacao_fisica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.localizacaofisica', verbose_name='Localização Física'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='militar_requisitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.militarrequisitante', verbose_name='Militar Requisitante'),
        ),
        migrations.AddField(
            model_name='militarrequisitante',
            name='orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='militares', to='estoque.orgaorequisitante', verbose_name='Órgão'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='orgao_requisitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.orgaorequisitante', verbose_name='Órgão Requisitante'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='unidade_fornecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.unidadefornecimento', verbose_name='Unidade de Fornecimento'),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_fornecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.unidadefornecimento', verbose_name='Unidade de Fornecimento Padrão'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['produto', '-data_movimentacao'], name='estoque_mov_produto_345496_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['subtipo', '-data_movimentacao'], name='estoque_mov_subtipo_df4d6b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['data_movimentacao'], name='estoque_mov_data_mo_0017da_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['status'], name='estoque_pro_status_5c16c9_idx'),
        ),
    ]
