# Generated by Django 5.2.4 on 2026-04-01 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_pap_dados_iniciais'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='empenho',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empenho'),
        ),
        migrations.AddField(
            model_name='produto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_subcategoria', to='estoque.categoria', verbose_name='Subcategoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_categoria', to='estoque.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Preparado para futura leitura por scanner', max_length=100, null=True, unique=True, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(help_text='Ex: Caneta Azul, Papel Sulfite A4', max_length=200, verbose_name='Nome do Material'),
        ),
    ]
