# Generated by Django 5.2.4 on 2026-04-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_remove_categoria_categoria_pai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='empenho',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº de Empenho'),
        ),
    ]
