# Generated by Django 5.2.4 on 2026-04-01 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_alter_produto_empenho'),
        ('policiais', '0002_alter_policial_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='militar_requisitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policiais.policial', verbose_name='Policial Requisitante'),
        ),
    ]
