# Generated by Django 5.2.13 on 2026-04-13 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_alter_movimentacaoestoque_militar_requisitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='militar_requisitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.militarrequisitante', verbose_name='Policial Requisitante'),
        ),
    ]
