# Generated by Django 5.2.13 on 2026-04-13 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_alter_movimentacaoestoque_militar_requisitante'),
        ('policiais', '0002_alter_policial_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='militar_administrativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.militarrequisitante', verbose_name='Militar Cadastrado (Adm)'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='militar_requisitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policiais.policial', verbose_name='Policial do Efetivo (BAEP)'),
        ),
    ]
