# Generated by Django 6.0.4 on 2026-04-27 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_movimentacaoestoque_militar_administrativo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogExclusaoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_material', models.CharField(max_length=50, verbose_name='Código')),
                ('nome_material', models.CharField(max_length=200, verbose_name='Nome')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('saldo_na_exclusao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo na Exclusão')),
                ('data_exclusao', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo / Justificativa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Exclusão de Material',
                'verbose_name_plural': 'Logs de Exclusão de Materiais',
                'ordering': ['-data_exclusao'],
            },
        ),
    ]
