# Generated by Django 5.2.13 on 2026-04-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_logexclusaomaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='disponivel_solicitacao',
            field=models.BooleanField(default=True, verbose_name='Disponível para Solicitação'),
        ),
    ]
