# Generated by Django 5.2.14 on 2026-05-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0015_adicionar_outra_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='descricao_outra_unidade',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Especificação da Outra Unidade'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='itens_por_embalagem',
            field=models.IntegerField(blank=True, null=True, verbose_name='Itens por Embalagem'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='quantidade_embalagens',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantidade de Embalagens'),
        ),
    ]
