# Generated by Django 5.2.14 on 2026-05-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0016_movimentacaoestoque_descricao_outra_unidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='recibo_assinado',
            field=models.FileField(blank=True, null=True, upload_to='recibos_assinados/', verbose_name='Recibo Assinado/Escaneado'),
        ),
    ]
