services:
  baep:
    build: .
    container_name: baep_app

    restart: always

    ports:
      - "8001:8000"

    volumes:
      - .:/app

    env_file:
      - .env

    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn --bind 0.0.0.0:8000 reserva_baep.wsgi:application
      "
