# Generated by Django 5.2.4 on 2025-07-30 17:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('SITUACAO_ATUAL', 'Situação Atual'), ('MATERIAIS_EM_USO', 'Materiais em Uso'), ('MATERIAIS_DISPONIVEIS', 'Materiais Disponíveis'), ('MOVIMENTACOES_DIA', 'Movimentações do Dia'), ('MOVIMENTACOES_PERIODO', 'Movimentações por Período'), ('MOVIMENTACOES_POLICIAL', 'Movimentações por Policial'), ('MOVIMENTACOES_MATERIAL', 'Movimentações por Material')], max_length=30, verbose_name='Tipo')),
                ('data_geracao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Geração')),
                ('periodo_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Período - Início')),
                ('periodo_fim', models.DateTimeField(blank=True, null=True, verbose_name='Período - Fim')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='relatorios/', verbose_name='Arquivo PDF')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('gerado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_gerados', to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-data_geracao'],
            },
        ),
    ]
