# Generated by Django 5.2.13 on 2026-04-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='modulo',
            field=models.CharField(choices=[('RESERVA', 'Reserva de Armas'), ('ESTOQUE', 'Almoxarifado/Estoque'), ('PATRIMONIO', 'Patrimônio')], default='RESERVA', max_length=20, verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='tipo',
            field=models.CharField(choices=[('SITUACAO_ATUAL', 'Situação Atual'), ('MATERIAIS_EM_USO', 'Materiais em Uso'), ('MATERIAIS_DISPONIVEIS', 'Materiais Disponíveis'), ('MOVIMENTACOES_DIA', 'Movimentações do Dia'), ('MOVIMENTACOES_PERIODO', 'Movimentações por Período'), ('MOVIMENTACOES_POLICIAL', 'Movimentações por Policial'), ('MOVIMENTACOES_MATERIAL', 'Movimentações por Material'), ('PATRIMONIO_INVENTARIO', 'Patrimônio: Inventário Geral'), ('PATRIMONIO_MOVIMENTACOES', 'Patrimônio: Histórico de Movimentações')], max_length=30, verbose_name='Tipo'),
        ),
    ]
