# Generated by Django 5.2.13 on 2026-04-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0003_alter_relatorio_modulo_alter_relatorio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='modulo',
            field=models.CharField(choices=[('RESERVA', 'Reserva de Armas'), ('ESTOQUE', 'Almoxarifado/Estoque'), ('PATRIMONIO', 'Patrimônio'), ('FROTA', 'Frota de Viaturas'), ('TELEMATICA', 'Telemática')], default='RESERVA', max_length=20, verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='tipo',
            field=models.CharField(choices=[('SITUACAO_ATUAL', 'Reserva: Situação Atual'), ('MATERIAIS_EM_USO', 'Reserva: Materiais em Uso'), ('MATERIAIS_DISPONIVEIS', 'Reserva: Materiais Disponíveis'), ('MOVIMENTACOES_PERIODO', 'Reserva: Movimentações por Período'), ('ESTOQUE_INVENTARIO', 'Estoque: Inventário Geral'), ('ESTOQUE_CRITICO', 'Estoque: Reposição Crítica'), ('ESTOQUE_MOVIMENTACOES', 'Estoque: Histórico de Movimentações'), ('PATRIMONIO_INVENTARIO', 'Patrimônio: Inventário Geral'), ('PATRIMONIO_MOVIMENTACOES', 'Patrimônio: Histórico de Movimentações'), ('FROTA_GERAL', 'Frota: Relatório Geral de Viaturas'), ('FROTA_ABASTECIMENTO', 'Frota: Relatório de Abastecimentos'), ('FROTA_MANUTENCAO', 'Frota: Histórico de Manutenções'), ('TELEMATICA_INVENTARIO', 'Telemática: Inventário de Ativos'), ('TELEMATICA_MANUTENCAO', 'Telemática: Histórico de Manutenções'), ('TELEMATICA_LINHAS', 'Telemática: Linhas Móveis e Chips')], max_length=30, verbose_name='Tipo'),
        ),
    ]
