# Generated by Django 6.0.4 on 2026-04-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0004_alter_relatorio_modulo_alter_relatorio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='parametros_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Parâmetros de Geração'),
        ),
    ]
