# Generated by Django 5.2.15 on 2026-07-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_belico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='am640',
            name='situacao',
            field=models.CharField(choices=[('KIT-01', 'KIT-01'), ('KIT-02', 'KIT-02'), ('KIT-03', 'KIT-03'), ('KIT-04', 'KIT-04'), ('KIT-05', 'KIT-05'), ('KIT-06', 'KIT-06'), ('KIT-07', 'KIT-07'), ('KIT-08', 'KIT-08'), ('KIT-09', 'KIT-09'), ('KIT-10', 'KIT-10'), ('RESERVA', 'Reserva'), ('CMT', 'Comandante'), ('EM_USO', 'Em Uso'), ('BAIXADO', 'Baixado')], default='RESERVA', max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='capacetebalistico',
            name='condicao',
            field=models.CharField(choices=[('OPERANDO', 'Operando'), ('EM_USO', 'Em Uso'), ('DANIFICADO', 'Danificado')], default='OPERANDO', max_length=20, verbose_name='Condição'),
        ),
        migrations.AlterField(
            model_name='coletebalistico',
            name='situacao',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_USO', 'Em Uso'), ('SINDICANCIA', 'Sindicância')], default='DISPONIVEL', max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='escudobalistico',
            name='situacao',
            field=models.CharField(choices=[('OP', 'Operacional'), ('EM_USO', 'Em Uso'), ('BXA', 'Baixado')], default='OP', max_length=10, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='espingardacal12',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('EM_USO', 'Em Uso'), ('BAIXADO', 'Baixado'), ('MANUTENCAO', 'Manutenção')], default='OK', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='fuzil',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('EM_USO', 'Em Uso'), ('BAIXADO', 'Baixado'), ('SINDICANCIA', 'Sindicância'), ('MANUTENCAO', 'Manutenção')], default='OK', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalam640',
            name='situacao',
            field=models.CharField(choices=[('KIT-01', 'KIT-01'), ('KIT-02', 'KIT-02'), ('KIT-03', 'KIT-03'), ('KIT-04', 'KIT-04'), ('KIT-05', 'KIT-05'), ('KIT-06', 'KIT-06'), ('KIT-07', 'KIT-07'), ('KIT-08', 'KIT-08'), ('KIT-09', 'KIT-09'), ('KIT-10', 'KIT-10'), ('RESERVA', 'Reserva'), ('CMT', 'Comandante'), ('EM_USO', 'Em Uso'), ('BAIXADO', 'Baixado')], default='RESERVA', max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='historicalcapacetebalistico',
            name='condicao',
            field=models.CharField(choices=[('OPERANDO', 'Operando'), ('EM_USO', 'Em Uso'), ('DANIFICADO', 'Danificado')], default='OPERANDO', max_length=20, verbose_name='Condição'),
        ),
        migrations.AlterField(
            model_name='historicalcoletebalistico',
            name='situacao',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_USO', 'Em Uso'), ('SINDICANCIA', 'Sindicância')], default='DISPONIVEL', max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='historicalescudobalistico',
            name='situacao',
            field=models.CharField(choices=[('OP', 'Operacional'), ('EM_USO', 'Em Uso'), ('BXA', 'Baixado')], default='OP', max_length=10, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='historicalespingardacal12',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('EM_USO', 'Em Uso'), ('BAIXADO', 'Baixado'), ('MANUTENCAO', 'Manutenção')], default='OK', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalfuzil',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('EM_USO', 'Em Uso'), ('BAIXADO', 'Baixado'), ('SINDICANCIA', 'Sindicância'), ('MANUTENCAO', 'Manutenção')], default='OK', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalpistolaglock',
            name='situacao_reserva',
            field=models.CharField(choices=[('ok', 'OK'), ('EM_USO', 'Em Uso'), ('APREENDIDA', 'Apreendida'), ('NOVIDADE', 'Novidade')], default='ok', max_length=20, verbose_name='Situação na Reserva'),
        ),
        migrations.AlterField(
            model_name='historicalradioht',
            name='situacao',
            field=models.CharField(choices=[('OP', 'Operacional'), ('EM_USO', 'Em Uso'), ('MANUTENCAO', 'Manutenção')], default='OP', max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='pistolaglock',
            name='situacao_reserva',
            field=models.CharField(choices=[('ok', 'OK'), ('EM_USO', 'Em Uso'), ('APREENDIDA', 'Apreendida'), ('NOVIDADE', 'Novidade')], default='ok', max_length=20, verbose_name='Situação na Reserva'),
        ),
        migrations.AlterField(
            model_name='radioht',
            name='situacao',
            field=models.CharField(choices=[('OP', 'Operacional'), ('EM_USO', 'Em Uso'), ('MANUTENCAO', 'Manutenção')], default='OP', max_length=20, verbose_name='Situação'),
        ),
    ]
