# Generated by Django 5.2.17 on 2026-10-07 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_belico', '0002_alter_am640_situacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltaser',
            name='carga_bateria_percent',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Carga da Bateria (%)'),
        ),
        migrations.AlterField(
            model_name='taser',
            name='carga_bateria_percent',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Carga da Bateria (%)'),
        ),
    ]
