# Generated by Django 5.2.13 on 2026-04-28 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0013_logexclusaomaterial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente (Aguardando Análise)'), ('EM_SEPARACAO', 'Em Separação'), ('PRONTO', 'Pronto para Retirada'), ('ENTREGUE', 'Entregue / Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações do Solicitante')),
                ('notas_admin', models.TextField(blank=True, null=True, verbose_name='Notas do Almoxarifado')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_feitas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação de Material',
                'verbose_name_plural': 'Solicitações de Materiais',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qtd. Solicitada')),
                ('quantidade_atendida', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qtd. Atendida')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto', verbose_name='Produto')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='solicitacoes.solicitacao', verbose_name='Solicitação')),
            ],
            options={
                'verbose_name': 'Item da Solicitação',
                'verbose_name_plural': 'Itens da Solicitação',
            },
        ),
    ]
