# Generated by Django 5.2.13 on 2026-04-28 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_produto_disponivel_solicitacao'),
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='orgao_requisitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.orgaorequisitante', verbose_name='Seção/Cia Requisitante'),
        ),
    ]
