# Generated by Django 6.0.4 on 2026-04-29 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policiais', '0002_alter_policial_data_atualizacao_and_more'),
        ('solicitacoes', '0002_solicitacao_orgao_requisitante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='entregue_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Entregue por'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='policial_requisitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_materiais', to='policiais.policial', verbose_name='Policial Requisitante'),
        ),
    ]
