# Generated by Django 6.0.4 on 2026-05-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0003_solicitacao_entregue_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exibir_quantidade_disponivel', models.BooleanField(default=True, verbose_name='Exibir Quantidade Disponível para Solicitantes')),
            ],
            options={
                'verbose_name': 'Configuração de Solicitação',
                'verbose_name_plural': 'Configurações de Solicitação',
            },
        ),
    ]
