# Generated by Django 5.2.14 on 2026-05-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0004_configuracaosolicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='descricao_outra_unidade',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Especificação da Outra Unidade'),
        ),
    ]
