# Generated by Django 6.0.4 on 2026-05-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100, unique=True, verbose_name='ID do Cliente')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('token_base64', models.TextField(verbose_name='Token Criptográfico')),
                ('issued_at', models.DateTimeField(verbose_name='Data de Emissão')),
                ('expires_at', models.DateTimeField(verbose_name='Data de Expiração')),
                ('last_verified', models.DateTimeField(auto_now=True, verbose_name='Última Verificação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Registro de Licença',
                'verbose_name_plural': 'Registros de Licença',
            },
        ),
    ]
