# Generated by Django 5.2.13 on 2026-05-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenserecord',
            name='client_id',
            field=models.CharField(max_length=100, verbose_name='ID do Cliente'),
        ),
    ]
