# Generated by Django 5.2.4 on 2025-07-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re', models.CharField(max_length=10, unique=True, verbose_name='RE')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('posto', models.CharField(choices=[('SD_PM', 'Sd PM'), ('CB_PM', 'Cb PM'), ('3SGT_PM', '3º Sgt PM'), ('2SGT_PM', '2º Sgt PM'), ('1SGT_PM', '1º Sgt PM'), ('SUBTEN_PM', 'Subten PM'), ('STEN_PM', 'Sten PM'), ('2TEN_PM', '2º Ten PM'), ('1TEN_PM', '1º Ten PM'), ('CAP_PM', 'Cap PM'), ('MAJ_PM', 'Maj PM'), ('TENCEL_PM', 'Ten Cel PM'), ('CEL_PM', 'Cel PM')], max_length=20, verbose_name='Posto/Graduação')),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('AFASTADO', 'Afastado'), ('TRANSFERIDO', 'Transferido')], default='ATIVO', max_length=20, verbose_name='Situação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='policiais/', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Policial',
                'verbose_name_plural': 'Policiais',
                'ordering': ['posto', 'nome'],
            },
        ),
    ]
