# Generated by Django 5.2.4 on 2026-02-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policiais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policial',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualização'),
        ),
        migrations.AlterField(
            model_name='policial',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cadastro'),
        ),
        migrations.AlterField(
            model_name='policial',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='policial',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Obs'),
        ),
        migrations.AlterField(
            model_name='policial',
            name='posto',
            field=models.CharField(choices=[('SD_PM', 'Sd PM'), ('CB_PM', 'Cb PM'), ('3SGT_PM', '3º Sgt PM'), ('2SGT_PM', '2º Sgt PM'), ('1SGT_PM', '1º Sgt PM'), ('SUBTEN_PM', 'Subten PM'), ('STEN_PM', 'Sten PM'), ('2TEN_PM', '2º Ten PM'), ('1TEN_PM', '1º Ten PM'), ('CAP_PM', 'Cap PM'), ('MAJ_PM', 'Maj PM'), ('TENCEL_PM', 'Ten Cel PM'), ('CEL_PM', 'Cel PM')], max_length=20, verbose_name='Posto'),
        ),
    ]
