# Generated by Django 5.2.13 on 2026-04-24 14:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policiais', '0002_alter_policial_data_atualizacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Categoria')),
                ('icone', models.CharField(default='fas fa-laptop', max_length=50, verbose_name='Ícone (FontAwesome)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria de Equipamento',
                'verbose_name_plural': 'Categorias de Equipamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ServicoTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Serviço')),
                ('tipo', models.CharField(choices=[('INTERNET', 'Link de Internet'), ('VPN', 'VPN / Acesso Remoto'), ('SISTEMA', 'Sistema Corporativo'), ('STORAGE', 'Backup / Armazenamento'), ('REDE', 'Infraestrutura de Rede')], max_length=20, verbose_name='Tipo')),
                ('fornecedor', models.CharField(max_length=150, verbose_name='Fornecedor/Órgão')),
                ('descricao', models.TextField(verbose_name='Descrição Técnica')),
                ('numero_contrato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº Contrato/Protocolo')),
                ('vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento/Renovação')),
                ('status', models.BooleanField(default=True, verbose_name='Em Operação?')),
                ('ip_publico', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Público/Gateway')),
                ('velocidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Velocidade/Capacidade')),
            ],
            options={
                'verbose_name': 'Serviço de TI',
                'verbose_name_plural': 'Serviços de TI',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Nº de Série')),
                ('patrimonio', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nº Patrimônio')),
                ('processador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Processador')),
                ('memoria_ram', models.CharField(blank=True, max_length=50, null=True, verbose_name='Memória RAM')),
                ('armazenamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Armazenamento (HD/SSD)')),
                ('sistema_operacional', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sistema Operacional')),
                ('hostname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome na Rede (Hostname)')),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('endereco_mac', models.CharField(blank=True, max_length=17, null=True, verbose_name='Endereço MAC')),
                ('vlan', models.CharField(blank=True, max_length=20, null=True, verbose_name='VLAN')),
                ('porta_switch', models.CharField(blank=True, max_length=50, null=True, verbose_name='Porta do Switch')),
                ('setor', models.CharField(max_length=100, verbose_name='Setor/Seção')),
                ('usuario_responsavel', models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuário Principal')),
                ('status', models.CharField(choices=[('OPERACIONAL', 'Operacional / Em Uso'), ('RESERVA', 'Reserva Técnica'), ('MANUTENCAO', 'Em Manutenção'), ('BAIXADO', 'Baixado / Inativo'), ('EXTRAVIADO', 'Extraviado / Roubado')], default='OPERACIONAL', max_length=20, verbose_name='Status')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('vencimento_garantia', models.DateField(blank=True, null=True, verbose_name='Vencimento da Garantia')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Técnicas')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='telematica.categoriaequipamento')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['categoria', 'hostname', 'patrimonio'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issi', models.CharField(help_text='Identificação Individual no Sistema', max_length=50, unique=True, verbose_name='ISSI')),
                ('tei', models.CharField(blank=True, help_text='Identificação do Equipamento', max_length=50, null=True, unique=True, verbose_name='TEI')),
                ('grupo_principal', models.CharField(max_length=100, verbose_name='Grupo de Conversação Principal')),
                ('criptografia_ativa', models.BooleanField(default=True, verbose_name='Criptografia Habilitada?')),
                ('versao_firmware', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versão de Firmware')),
                ('equipamento', models.OneToOneField(limit_choices_to={'categoria__nome__icontains': 'Rádio'}, on_delete=django.db.models.deletion.CASCADE, related_name='config_radio', to='telematica.equipamento')),
            ],
            options={
                'verbose_name': 'Configuração de Rádio',
                'verbose_name_plural': 'Configurações de Rádios',
            },
        ),
        migrations.CreateModel(
            name='LinhaMovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número do Telefone')),
                ('operadora', models.CharField(max_length=50, verbose_name='Operadora')),
                ('iccid', models.CharField(max_length=30, unique=True, verbose_name='ICCID (Nº do Chip)')),
                ('imei_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='IMEI 1')),
                ('imei_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='IMEI 2')),
                ('plano_dados', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plano/Cota de Dados')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('equipamento_vinculado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linha_movel', to='telematica.equipamento')),
                ('policial_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linhas_telematica', to='policiais.policial')),
            ],
            options={
                'verbose_name': 'Linha Móvel',
                'verbose_name_plural': 'Linhas Móveis',
            },
        ),
        migrations.CreateModel(
            name='ManutencaoTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRETIVA', 'Corretiva / Reparo'), ('UPGRADE', 'Upgrade / Melhoria'), ('SOFTWARE', 'Instalação/Configuração Software')], max_length=20, verbose_name='Tipo de Manutenção')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('descricao_problema', models.TextField(verbose_name='Descrição do Problema / Solicitação')),
                ('solucao_tecnica', models.TextField(blank=True, null=True, verbose_name='Solução Aplicada')),
                ('tecnico_responsavel', models.CharField(max_length=150, verbose_name='Técnico Responsável')),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo (R$)')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída?')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes_ti', to='telematica.equipamento')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manutenção de TI',
                'verbose_name_plural': 'Manutenções de TI',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
