# Generated by Django 5.2.13 on 2026-04-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telematica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='codigo_unidade',
            field=models.CharField(blank=True, help_text='Ex: 02BAEP, 1BPRv, etc.', max_length=50, null=True, verbose_name='Cód. da Unidade'),
        ),
    ]
