# Generated by Django 5.2.13 on 2026-04-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telematica', '0002_equipamento_codigo_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('OPERACIONAL', 'Operacional / Em Uso'), ('RESERVA', 'Reserva Técnica'), ('MANUTENCAO', 'Em Manutenção'), ('DISPOSICAO', 'À disposição de outra unidade'), ('BAIXADO', 'Baixado / Inativo'), ('EXTRAVIADO', 'Extraviado / Roubado')], default='OPERACIONAL', max_length=20, verbose_name='Status'),
        ),
    ]
