# Generated by Django 5.2.13 on 2026-04-28 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_produto_disponivel_solicitacao'),
        ('telematica', '0003_alter_equipamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='orgao_setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='estoque.orgaorequisitante', verbose_name='Órgão/Setor'),
        ),
    ]
