# Generated by Django 5.2.13 on 2026-04-28 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_produto_disponivel_solicitacao'),
        ('telematica', '0004_equipamento_orgao_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='setor',
        ),
        migrations.RenameField(
            model_name='equipamento',
            old_name='orgao_setor',
            new_name='setor',
        ),
    ]
