# Generated by Django 5.2.13 on 2026-04-28 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_produto_disponivel_solicitacao'),
        ('policiais', '0002_alter_policial_data_atualizacao_and_more'),
        ('telematica', '0005_remove_equipamento_orgao_setor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='policial_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='policiais.policial', verbose_name='Policial Responsável'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='estoque.orgaorequisitante', verbose_name='Setor/Seção'),
        ),
    ]
