# Generated by Django 5.2.13 on 2026-04-28 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policiais', '0002_alter_policial_data_atualizacao_and_more'),
        ('telematica', '0006_equipamento_policial_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencaoti',
            name='policial_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes_realizadas', to='policiais.policial', verbose_name='Técnico Policial'),
        ),
    ]
