# Generated by Django 6.0.4 on 2026-04-29 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policiais', '0002_alter_policial_data_atualizacao_and_more'),
        ('telematica', '0007_manutencaoti_policial_tecnico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoSuporteTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('tipo_servico', models.CharField(choices=[('HARDWARE', 'Hardware (Computador, Monitor, Impressora)'), ('SOFTWARE', 'Software / Instalação de Sistemas'), ('REDE', 'Rede / Conexão / Internet'), ('RADIO', 'Rádio / Comunicação Crítica'), ('CELULAR', 'Celular / Tablet / Chip'), ('SISTEMA_BAEP', 'Sistema de Controle BAEP'), ('OUTRO', 'Outros Assuntos')], max_length=20, verbose_name='Tipo de Serviço')),
                ('descricao_problema', models.TextField(verbose_name='Descrição do Problema / Solicitação')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa (Pode aguardar)'), ('MEDIA', 'Média (Uso diário)'), ('ALTA', 'Alta (Equipamento inoperante)'), ('URGENTE', 'Urgente (Parada Operacional/Emergência)')], default='MEDIA', max_length=20, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente (Aguardando Triagem)'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('AGUARDANDO_PECA', 'Aguardando Peça/Terceiro'), ('CONCLUIDA', 'Concluída / Resolvida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('solucao_tecnica', models.TextField(blank=True, null=True, verbose_name='Solução / Parecer Técnico')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suportes', to='telematica.equipamento', verbose_name='Equipamento Relacionado')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suportes_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('tecnico_atribuido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suportes_atribuidos', to='policiais.policial', verbose_name='Técnico Atribuído')),
            ],
            options={
                'verbose_name': 'Solicitação de Suporte TI',
                'verbose_name_plural': 'Solicitações de Suporte TI',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
