# Generated by Django 6.0.4 on 2026-04-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telematica', '0008_solicitacaosuporteti'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaosuporteti',
            name='tecnico_externo',
            field=models.CharField(blank=True, help_text='Preencha caso o técnico não seja do efetivo', max_length=150, null=True, verbose_name='Técnico Externo / Empresa'),
        ),
    ]
