# Generated by Django 6.0.4 on 2026-04-29 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telematica', '0009_solicitacaosuporteti_tecnico_externo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaosuporteti',
            options={'ordering': ['-data_solicitacao'], 'verbose_name': 'Suporte Técnico / Chamado', 'verbose_name_plural': 'Suportes Técnicos / Chamados'},
        ),
        migrations.AddField(
            model_name='solicitacaosuporteti',
            name='aberto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suportes_criados', to=settings.AUTH_USER_MODEL, verbose_name='Aberto por'),
        ),
        migrations.AddField(
            model_name='solicitacaosuporteti',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo (R$)'),
        ),
        migrations.AddField(
            model_name='solicitacaosuporteti',
            name='data_inicio_atendimento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início do Atendimento'),
        ),
        migrations.AddField(
            model_name='solicitacaosuporteti',
            name='origem',
            field=models.CharField(choices=[('USUARIO', 'Portal do Usuário'), ('INTERNO', 'Abertura Interna (Telemática)')], default='USUARIO', max_length=10, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='solicitacaosuporteti',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura'),
        ),
        migrations.AlterField(
            model_name='solicitacaosuporteti',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suportes_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante/Interessado'),
        ),
        migrations.AlterField(
            model_name='solicitacaosuporteti',
            name='tecnico_externo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Técnico Externo / Empresa'),
        ),
        migrations.AlterField(
            model_name='solicitacaosuporteti',
            name='tipo_servico',
            field=models.CharField(choices=[('HARDWARE', 'Hardware (Computador, Monitor, Impressora)'), ('SOFTWARE', 'Software / Instalação de Sistemas'), ('REDE', 'Rede / Conexão / Internet'), ('RADIO', 'Rádio / Comunicação Crítica'), ('CELULAR', 'Celular / Tablet / Chip'), ('SISTEMA_BAEP', 'Sistema de Controle BAEP'), ('PREVENTIVA', 'Manutenção Preventiva'), ('CORRETIVA', 'Manutenção Corretiva / Reparo'), ('OUTRO', 'Outros Assuntos')], max_length=20, verbose_name='Tipo de Serviço'),
        ),
        migrations.DeleteModel(
            name='ManutencaoTI',
        ),
    ]
