# Generated by Django 5.2.4 on 2025-07-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ARMA', 'Arma'), ('MUNICAO', 'Munição'), ('COLETE', 'Colete'), ('RADIO', 'Rádio'), ('ALGEMA', 'Algema'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Total')),
                ('quantidade_disponivel', models.PositiveIntegerField(verbose_name='Quantidade Disponível')),
                ('quantidade_em_uso', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Uso')),
                ('estado', models.CharField(choices=[('NOVO', 'Novo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('PESSIMO', 'Péssimo')], max_length=20, verbose_name='Estado')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_USO', 'Em Uso'), ('MANUTENCAO', 'Manutenção'), ('APREENDIDO', 'Apreendido'), ('BAIXADO', 'Baixado')], max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='materiais/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['tipo', 'nome'],
            },
        ),
    ]
