# Generated by Django 5.2.13 on 2026-04-13 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_movimentacaoestoque_militar_administrativo_and_more'),
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='localizacao_fisica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.localizacaofisica', verbose_name='Localização Física'),
        ),
    ]
