# Generated by Django 5.2.13 on 2026-04-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0002_material_localizacao_fisica'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='categoria',
            field=models.CharField(blank=True, choices=[('PISTOLA', 'Pistola'), ('FUZIL', 'Fuzil'), ('CAL_12', 'Calibre 12'), ('SUBMETRALHADORA', 'Submetralhadora'), ('LANCADOR', 'Lançador'), ('CHOQUE', 'Menos que Letal / Choque'), ('OUTROS', 'Outros')], default='OUTROS', max_length=30, null=True, verbose_name='Categoria'),
        ),
    ]
