# Generated by Django 5.2.14 on 2026-05-26 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0003_material_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteMunicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibre', models.CharField(max_length=50, verbose_name='Calibre')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca/Fabricante')),
                ('numero_lote', models.CharField(max_length=100, verbose_name='Número do Lote')),
                ('tipo_municao', models.CharField(choices=[('REAL', 'Real'), ('TREINAMENTO', 'Treinamento'), ('FESTIM', 'Festim'), ('ELASTOMERO', 'Elastômero')], default='REAL', max_length=20, verbose_name='Tipo de Munição')),
                ('data_fabricacao', models.DateField(blank=True, null=True, verbose_name='Data de Fabricação')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('quantidade_inicial', models.PositiveIntegerField(verbose_name='Quantidade Inicial')),
                ('quantidade_atual', models.PositiveIntegerField(verbose_name='Quantidade Atual')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_municao', to='materiais.material', verbose_name='Material (Munição)')),
            ],
            options={
                'verbose_name': 'Lote de Munição',
                'verbose_name_plural': 'Lotes de Munição',
                'ordering': ['data_validade', 'numero_lote'],
                'unique_together': {('material', 'numero_lote')},
            },
        ),
    ]
