# Generated by Django 5.2.4 on 2025-07-30 17:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiais', '0001_initial'),
        ('policiais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('tipo', models.CharField(choices=[('RETIRADA', 'Retirada'), ('DEVOLUCAO', 'Devolução')], max_length=10, verbose_name='Tipo')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='materiais.material', verbose_name='Material')),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='policiais.policial', verbose_name='Policial')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Retirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prevista_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data Prevista para Devolução')),
                ('finalidade', models.CharField(max_length=100, verbose_name='Finalidade')),
                ('local_uso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Local de Uso')),
                ('movimentacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retirada', to='movimentacoes.movimentacao', verbose_name='Movimentação')),
            ],
            options={
                'verbose_name': 'Retirada',
                'verbose_name_plural': 'Retiradas',
                'ordering': ['-movimentacao__data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_devolucao', models.CharField(choices=[('NOVO', 'Novo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('PESSIMO', 'Péssimo')], max_length=20, verbose_name='Estado na Devolução')),
                ('movimentacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devolucao', to='movimentacoes.movimentacao', verbose_name='Movimentação')),
                ('retirada_referencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='movimentacoes.retirada', verbose_name='Retirada de Referência')),
            ],
            options={
                'verbose_name': 'Devolução',
                'verbose_name_plural': 'Devoluções',
                'ordering': ['-movimentacao__data_hora'],
            },
        ),
    ]
