# Generated by Django 5.2.14 on 2026-05-26 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0004_lotemunicao'),
        ('movimentacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='lote_municao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='materiais.lotemunicao', verbose_name='Lote de Munição'),
        ),
        migrations.CreateModel(
            name='RegistroDisparoMunicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_disparada', models.PositiveIntegerField(default=0, verbose_name='Munições Disparadas')),
                ('quantidade_extraviada', models.PositiveIntegerField(default=0, verbose_name='Munições Extraviadas')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa/Ocorrência')),
                ('boletim_ocorrencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do B.O.')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('devolucao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_disparo', to='movimentacoes.devolucao', verbose_name='Devolução')),
            ],
            options={
                'verbose_name': 'Registro de Disparo/Extravio',
                'verbose_name_plural': 'Registros de Disparos/Extravios',
                'ordering': ['-data_registro'],
            },
        ),
    ]
