# Generated by Django 5.2.14 on 2026-05-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0002_movimentacao_lote_municao_registrodisparomunicao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrodisparomunicao',
            options={'ordering': ['-data_registro'], 'verbose_name': 'Registro de Disparo/Extravio', 'verbose_name_plural': 'Registros de Disparos/Extravios'},
        ),
        migrations.AlterField(
            model_name='registrodisparomunicao',
            name='boletim_ocorrencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do B.O.'),
        ),
        migrations.AlterField(
            model_name='registrodisparomunicao',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro'),
        ),
        migrations.AlterField(
            model_name='registrodisparomunicao',
            name='justificativa',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa/Ocorrência'),
        ),
        migrations.AlterField(
            model_name='registrodisparomunicao',
            name='quantidade_disparada',
            field=models.PositiveIntegerField(default=0, verbose_name='Munições Disparadas'),
        ),
        migrations.AlterField(
            model_name='registrodisparomunicao',
            name='quantidade_extraviada',
            field=models.PositiveIntegerField(default=0, verbose_name='Munições Extraviadas'),
        ),
    ]
