# Generated by Django 5.2.14 on 2026-08-13 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(default='fa-solid fa-book-open', help_text='Classe FontAwesome, ex: "fa-solid fa-boxes"', max_length=80, verbose_name='Ícone (FontAwesome)')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do Módulo')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('grupo', models.CharField(blank=True, help_text='Grupo do sistema que abre este módulo (ex: reserva_armas). Vazio = aberto a todos os usuários logados.', max_length=50, verbose_name='Grupo de Acesso (permissão)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
            ],
            options={
                'verbose_name': 'Módulo do Tutorial',
                'verbose_name_plural': 'Módulos do Tutorial',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='SecaoTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('conteudo', models.TextField(help_text='HTML (tags básicas, classes Bootstrap permitidas).', verbose_name='Conteúdo')),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('PASSO', 'Passo a Passo'), ('DICA', 'Dica'), ('ALERTA', 'Alerta / Regra'), ('TABELA', 'Tabela')], default='TEXTO', max_length=20, verbose_name='Tipo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes', to='tutorial.modulotutorial')),
            ],
            options={
                'verbose_name': 'Seção do Tutorial',
                'verbose_name_plural': 'Seções do Tutorial',
                'ordering': ['modulo', 'ordem'],
                'unique_together': {('modulo', 'titulo')},
            },
        ),
    ]
