# Generated by Django 5.2.4 on 2026-04-07 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policiais', '0002_alter_policial_data_atualizacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaViatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Marca')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ModeloViatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Modelo')),
                ('tipo', models.CharField(choices=[('4_RODAS', 'Quatro Rodas (Carro/SUV/Pick-up)'), ('MOTO', 'Motocicleta'), ('EMBARCACAO', 'Embarcação'), ('CAMINHAO', 'Caminhão/Micro-ônibus')], max_length=20, verbose_name='Tipo de Viatura')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='viaturas.marcaviatura')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['marca__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(help_text='Ex: E-10201', max_length=20, unique=True, verbose_name='Prefixo da Viatura')),
                ('placa', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Placa')),
                ('chassi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chassi/Nº de Série')),
                ('renavam', models.CharField(blank=True, max_length=30, null=True, verbose_name='RENAVAM')),
                ('ano_fabricacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de Fabricação')),
                ('cor', models.CharField(default='Cinza/PM', max_length=30, verbose_name='Cor Predominante')),
                ('tipo_combustivel', models.CharField(choices=[('FLEX', 'Flex (Álcool/Gasolina)'), ('GASOLINA', 'Gasolina'), ('ALCOOL', 'Etanol'), ('DIESEL', 'Diesel'), ('ELETRICO', 'Elétrico (kWh)'), ('OUTRO', 'Outro')], default='FLEX', max_length=20, verbose_name='Tipo de Combustível Padrão')),
                ('capacidade_tanque', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Capacidade do Tanque (L)')),
                ('odometro_atual', models.DecimalField(decimal_places=1, default=0, help_text='Km ou Horas(embarcação)', max_digits=10, verbose_name='Odômetro/Horímetro Atual')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível (Pronta para uso)'), ('EM_USO', 'Em Uso (Despachada)'), ('MANUTENCAO', 'Em Manutenção/Oficina'), ('BAIXADA', 'Baixada/Inativa')], default='DISPONIVEL', max_length=20, verbose_name='Status Atual')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viaturas', to='viaturas.modeloviatura')),
            ],
            options={
                'verbose_name': 'Viatura',
                'verbose_name_plural': 'Viaturas',
                'ordering': ['modelo__tipo', 'prefixo'],
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREVENTIVA', 'Preventiva (Revisão, Óleo, Pneus)'), ('CORRETIVA', 'Corretiva (Quebra, Acidente)')], max_length=20, verbose_name='Tipo de Manutenção')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('odometro', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Odômetro na Manutenção')),
                ('descricao', models.TextField(verbose_name='Descrição dos Serviços/Peças')),
                ('oficina', models.CharField(max_length=150, verbose_name='Oficina/Empresa')),
                ('custo_pecas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Peças (R$)')),
                ('custo_mao_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Mão de Obra (R$)')),
                ('ordem_servico', models.CharField(blank=True, max_length=50, null=True, verbose_name='O.S. Nº')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes', to='viaturas.viatura')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DespachoViatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Saída')),
                ('km_saida', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Odômetro na Saída')),
                ('data_retorno', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Retorno')),
                ('km_retorno', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Odômetro no Retorno')),
                ('observacoes_saida', models.TextField(blank=True, null=True, verbose_name='Avarias/Obs na Saída')),
                ('observacoes_retorno', models.TextField(blank=True, null=True, verbose_name='Avarias/Obs no Retorno')),
                ('encarregado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_encarregado', to='policiais.policial', verbose_name='Encarregado/Cmt Eqp')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos_motorista', to='policiais.policial', verbose_name='Motorista')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Despachante')),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='viaturas.viatura')),
            ],
            options={
                'verbose_name': 'Despacho de Viatura',
                'verbose_name_plural': 'Despachos de Viaturas',
                'ordering': ['-data_saida'],
            },
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abastecimento', models.DateTimeField(verbose_name='Data e Hora')),
                ('odometro', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Odômetro no momento')),
                ('combustivel', models.CharField(choices=[('FLEX', 'Flex (Álcool/Gasolina)'), ('GASOLINA', 'Gasolina'), ('ALCOOL', 'Etanol'), ('DIESEL', 'Diesel'), ('ELETRICO', 'Elétrico (kWh)'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo Utilizado')),
                ('quantidade_litros', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantidade (Litros)')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total (R$)')),
                ('cupom_fiscal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cupom Fiscal/Requisição')),
                ('posto_fornecedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Posto/Fornecedor')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policiais.policial', verbose_name='Quem abasteceu')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos', to='viaturas.viatura')),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
                'ordering': ['-data_abastecimento'],
            },
        ),
    ]
