# Generated by Django 5.2.13 on 2026-04-17 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0002_create_frota_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome/Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('cidade', models.CharField(default='Santos', max_length=100, verbose_name='Cidade')),
                ('telefone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone/WhatsApp')),
                ('contato_responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Contato')),
                ('especialidade', models.CharField(blank=True, help_text='Ex: Funilaria, Mecânica Diesel, Elétrica', max_length=100, null=True, verbose_name='Especialidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='oficina',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Oficina (Texto)'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='oficina_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes', to='viaturas.oficina', verbose_name='Oficina (Cadastrada)'),
        ),
    ]
