# Generated by Django 5.2.13 on 2026-04-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0003_oficina_alter_manutencao_oficina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Em Aberto'), ('AGUARDANDO_PECA', 'Aguardando Peça'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20, verbose_name='Status'),
        ),
    ]
