# Generated by Django 5.2.13 on 2026-04-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0004_manutencao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='viatura',
            name='numero_patrimonio',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nº Patrimônio'),
        ),
    ]
