# Generated by Django 5.2.13 on 2026-04-17 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policiais', '0002_alter_policial_data_atualizacao_and_more'),
        ('viaturas', '0005_viatura_numero_patrimonio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manutencao',
            options={},
        ),
        migrations.CreateModel(
            name='ChecklistViatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SAIDA', 'Saída de Serviço'), ('RETORNO', 'Retorno de Serviço'), ('ROTINA', 'Inspeção de Rotina/Semanal')], default='SAIDA', max_length=20, verbose_name='Tipo de Checklist')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('odometro', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Odômetro Atual')),
                ('limpeza_interna', models.BooleanField(default=True, verbose_name='Limpeza Interna OK?')),
                ('limpeza_externa', models.BooleanField(default=True, verbose_name='Limpeza Externa OK?')),
                ('conservacao_estofados', models.BooleanField(default=True, verbose_name='Estofados/Bancos OK?')),
                ('niveis_fluidos', models.BooleanField(default=True, verbose_name='Níveis de Óleo/Água OK?')),
                ('pneus_condicoes', models.BooleanField(default=True, verbose_name='Pneus em boas condições?')),
                ('pneu_estepe', models.BooleanField(default=True, verbose_name='Pneu Estepe presente/cheio?')),
                ('freio_estacionamento', models.BooleanField(default=True, verbose_name='Freio de Mão OK?')),
                ('farois_lanternas', models.BooleanField(default=True, verbose_name='Faróis e Lanternas OK?')),
                ('setas_emergencia', models.BooleanField(default=True, verbose_name='Setas/Pisca-alerta OK?')),
                ('giroflex_sirene', models.BooleanField(default=True, verbose_name='Giroflex e Sirene OK?')),
                ('painel_instrumentos', models.BooleanField(default=True, verbose_name='Instrumentos do Painel OK?')),
                ('extintor_incendio', models.BooleanField(default=True, verbose_name='Extintor (Carga/Validade) OK?')),
                ('triangulo_macaco_chave', models.BooleanField(default=True, verbose_name='Triângulo/Macaco/Chave Roda OK?')),
                ('cones_sinalizacao', models.BooleanField(default=True, verbose_name='Cones de Sinalização OK?')),
                ('documentacao_crlv', models.BooleanField(default=True, verbose_name='Documentação (CRLV) OK?')),
                ('kit_primeiros_socorros', models.BooleanField(default=True, verbose_name='Kit Primeiros Socorros OK?')),
                ('avarias_lataria', models.TextField(blank=True, help_text='Descreva riscos, mossas ou quebras', null=True, verbose_name='Avarias na Lataria/Pintura')),
                ('observacoes_gerais', models.TextField(blank=True, null=True, verbose_name='Observações Gerais')),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='policiais.policial', verbose_name='Avaliador')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='viaturas.viatura')),
            ],
            options={
                'verbose_name': 'Checklist de Viatura',
                'verbose_name_plural': 'Checklists de Viaturas',
                'ordering': ['-data_hora'],
            },
        ),
    ]
