# Generated by Django 5.2.13 on 2026-04-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0006_alter_manutencao_options_checklistviatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='viatura',
            name='localizacao',
            field=models.CharField(blank=True, default='Base BAEP', help_text='Onde a viatura se encontra fisicamente', max_length=150, null=True, verbose_name='Localização Atual'),
        ),
    ]
