# Generated by Django 5.2.13 on 2026-04-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0007_viatura_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viatura',
            name='localizacao',
            field=models.CharField(choices=[('1_CIA', '1ª CIA'), ('2_CIA', '2ª CIA'), ('3_CIA', '3ª CIA'), ('4_CIA', '4ª CIA'), ('EM', 'EM'), ('P4', 'P4'), ('MOTOMEC', 'MOTOMEC'), ('OFICINA', 'Oficina'), ('EM_USO', 'Em Uso / Despachada')], default='MOTOMEC', max_length=20, verbose_name='Localização Atual'),
        ),
    ]
