# Generated by Django 5.2.13 on 2026-04-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0008_alter_viatura_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='data_validade_garantia',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da Garantia (Data)'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='detalhamento_pecas_garantia',
            field=models.TextField(blank=True, null=True, verbose_name='Peças Trocadas e Condições de Garantia'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='detalhamento_servicos',
            field=models.TextField(blank=True, help_text='O que foi efetivamente feito na oficina', null=True, verbose_name='Detalhamento dos Serviços (Pós-Manutenção)'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='km_validade_garantia',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Validade da Garantia (Km)'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='nota_fiscal',
            field=models.FileField(blank=True, null=True, upload_to='viaturas/manutencao/notas/', verbose_name='Nota Fiscal (Anexo)'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='servicos_executados_corretamente',
            field=models.BooleanField(default=False, help_text='Marque após a verificação/teste da viatura', verbose_name='Serviços executados corretamente?'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='termo_garantia',
            field=models.FileField(blank=True, null=True, upload_to='viaturas/manutencao/garantias/', verbose_name='Termo de Garantia (Anexo)'),
        ),
    ]
