# Generated by Django 5.2.13 on 2026-04-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0009_manutencao_data_validade_garantia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='status',
            field=models.CharField(choices=[('AGENDADA', 'Agendada (Futura)'), ('ABERTA', 'Em Aberto'), ('AGUARDANDO_PECA', 'Aguardando Peça'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20, verbose_name='Status'),
        ),
    ]
