# Generated by Django 6.0.4 on 2026-04-29 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0010_alter_manutencao_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoBaixaViatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='Motivo da Baixa/Descarga')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente (Aguardando Análise)'), ('APROVADA', 'Aprovada'), ('NEGADA', 'Negada/Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('observacoes_admin', models.TextField(blank=True, null=True, verbose_name='Observações/Parecer')),
                ('data_analise', models.DateTimeField(blank=True, null=True)),
                ('analisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baixas_analisadas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baixas_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_baixa', to='viaturas.viatura')),
            ],
            options={
                'verbose_name': 'Solicitação de Baixa de Viatura',
                'verbose_name_plural': 'Solicitações de Baixa de Viatura',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
