# Generated by Django 6.0.4 on 2026-05-04 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policiais', '0002_alter_policial_data_atualizacao_and_more'),
        ('viaturas', '0011_solicitacaobaixaviatura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaobaixaviatura',
            name='categoria_motivo',
            field=models.CharField(choices=[('INSERVIVEL', 'Inservível / Fim de Vida Útil'), ('ACIDENTE', 'Acidente / Perda Total'), ('REPASSE', 'Repasse / Transferência'), ('LEILAO', 'Destinação para Leilão'), ('MANUTENCAO_EXCESSIVA', 'Custo de Manutenção Excessivo'), ('OUTROS', 'Outros Motivos')], default='INSERVIVEL', max_length=25, verbose_name='Categoria da Baixa'),
        ),
        migrations.AddField(
            model_name='solicitacaobaixaviatura',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baixas_como_motorista', to='policiais.policial', verbose_name='Motorista Responsável'),
        ),
        migrations.AddField(
            model_name='solicitacaobaixaviatura',
            name='quilometragem_baixa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Quilometragem/Horímetro na Baixa'),
        ),
        migrations.AddField(
            model_name='solicitacaobaixaviatura',
            name='requisitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baixas_requisitadas', to='policiais.policial', verbose_name='Policial Requisitante'),
        ),
        migrations.AlterField(
            model_name='solicitacaobaixaviatura',
            name='motivo',
            field=models.TextField(verbose_name='Justificativa Detalhada'),
        ),
        migrations.AlterField(
            model_name='solicitacaobaixaviatura',
            name='observacoes_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Observações/Parecer do Gestor'),
        ),
        migrations.AlterField(
            model_name='solicitacaobaixaviatura',
            name='solicitante',
            field=models.ForeignKey(help_text='Usuário logado que registrou', on_delete=django.db.models.deletion.CASCADE, related_name='baixas_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
