# Generated by Django 6.0.4 on 2026-05-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0012_solicitacaobaixaviatura_categoria_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaobaixaviatura',
            name='categoria_motivo',
            field=models.CharField(choices=[('PREVENTIVA', 'Manutenção Preventiva'), ('SUBSTITUICAO', 'Substituição de Peças'), ('QUEBRA', 'Quebra / Defeito Mecânico'), ('ACIDENTE', 'Acidente / Sinistro'), ('INSERVIVEL', 'Inservível / Fim de Vida Útil'), ('REPASSE', 'Repasse / Transferência'), ('LEILAO', 'Destinação para Leilão'), ('OUTROS', 'Outros Motivos')], default='INSERVIVEL', max_length=25, verbose_name='Categoria da Baixa'),
        ),
        migrations.AlterField(
            model_name='solicitacaobaixaviatura',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente (Aguardando Análise)'), ('MANUTENCAO', 'Encaminhar para Manutenção'), ('OFICINA', 'Encaminhar para Oficina'), ('AGUARDAR_VISTORIA', 'Aguardar Vistoria'), ('MOTOMEC', 'Encaminhar para MOTOMEC'), ('PREGAO', 'Destinar para Pregão'), ('DESCARGA', 'Efetuar Descarga (Baixa Definitiva)'), ('NEGADA', 'Negada/Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível (Pronta para uso)'), ('EM_USO', 'Em Uso (Despachada)'), ('MANUTENCAO', 'Em Manutenção/Oficina'), ('VISTORIA', 'Aguardando Vistoria'), ('PREGAO', 'Para Pregão'), ('BAIXADA', 'Baixada/Inativa')], default='DISPONIVEL', max_length=20, verbose_name='Status Atual'),
        ),
    ]
