# Generated by Django 6.0.4 on 2026-05-05 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policiais', '0002_alter_policial_data_atualizacao_and_more'),
        ('viaturas', '0013_alter_solicitacaobaixaviatura_categoria_motivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PecaViatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Peça')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código/Part Number')),
                ('quantidade_estoque', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('limite_minimo', models.PositiveIntegerField(default=0, verbose_name='Estoque Mínimo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Peça de Viatura',
                'verbose_name_plural': 'Peças de Viaturas',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='viatura',
            name='localizacao',
            field=models.CharField(choices=[('1_CIA', '1ª CIA'), ('2_CIA', '2ª CIA'), ('3_CIA', '3ª CIA'), ('4_CIA', '4ª CIA'), ('EM', 'EM'), ('P4', 'P4'), ('MOTOMEC', 'MOTOMEC'), ('OFICINA', 'Oficina'), ('EM_USO', 'Em Serviço Administrativo')], default='MOTOMEC', max_length=20, verbose_name='Localização Atual'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível (Pronta para uso)'), ('EM_USO', 'Em Serviço Administrativo'), ('MANUTENCAO', 'Em Manutenção/Oficina'), ('VISTORIA', 'Aguardando Vistoria'), ('PREGAO', 'Para Pregão'), ('BAIXADA', 'Baixada/Inativa')], default='DISPONIVEL', max_length=20, verbose_name='Status Atual'),
        ),
        migrations.CreateModel(
            name='RetiradaPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações/Justificativa')),
                ('assinado_eletronicamente', models.BooleanField(default=False, verbose_name='Assinado Eletronicamente?')),
                ('arquivo_recibo', models.FileField(blank=True, null=True, upload_to='viaturas/recibos_pecas/', verbose_name='Recibo de Retirada')),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiradas_pecas', to='policiais.policial', verbose_name='Policial que Retirou')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiradas_pecas', to='viaturas.viatura', verbose_name='Viatura de Destino')),
            ],
            options={
                'verbose_name': 'Retirada de Peça',
                'verbose_name_plural': 'Retiradas de Peças',
                'ordering': ['-data_retirada'],
            },
        ),
        migrations.CreateModel(
            name='RetiradaPecaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viaturas.pecaviatura')),
                ('retirada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='viaturas.retiradapeca')),
            ],
            options={
                'verbose_name': 'Item da Retirada de Peça',
                'verbose_name_plural': 'Itens da Retirada de Peça',
            },
        ),
    ]
