# Generated by Django 6.0.4 on 2026-05-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaturas', '0014_pecaviatura_alter_viatura_localizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecaviatura',
            name='aplicacao',
            field=models.TextField(blank=True, null=True, verbose_name='Aplicação (Modelos Compatíveis)'),
        ),
        migrations.AddField(
            model_name='pecaviatura',
            name='categoria',
            field=models.CharField(choices=[('MOTOR', 'Motor e Componentes'), ('SUSPENSAO', 'Suspensão e Direção'), ('FREIOS', 'Freios'), ('ELETRICA', 'Elétrica e Iluminação'), ('TRANSMISSAO', 'Transmissão e Embreagem'), ('CARROCERIA', 'Carroceria e Acabamento'), ('LUBRIFICANTES', 'Fluidos e Lubrificantes'), ('OUTROS', 'Outros/Geral')], default='OUTROS', max_length=30, verbose_name='Categoria/Sistema'),
        ),
        migrations.AddField(
            model_name='pecaviatura',
            name='localizacao_estoque',
            field=models.CharField(blank=True, help_text='Ex: Prateleira 2, Gaveta A', max_length=100, null=True, verbose_name='Localização no Estoque'),
        ),
        migrations.AddField(
            model_name='pecaviatura',
            name='marca_fabricante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca/Fabricante'),
        ),
        migrations.AddField(
            model_name='pecaviatura',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Gerais'),
        ),
        migrations.AddField(
            model_name='pecaviatura',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Unitário Estimado (R$)'),
        ),
    ]
