# Generated by Django 5.2.15 on 2026-06-12 14:58

import django.core.validators
import viaturas.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policiais', '0002_alter_policial_data_atualizacao_and_more'),
        ('viaturas', '0018_documentoviatura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmanutencao',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Manutenção', 'verbose_name_plural': 'historical Manutenções'},
        ),
        migrations.AlterModelOptions(
            name='manutencao',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Manutenção', 'verbose_name_plural': 'Manutenções'},
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='odometro',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Odômetro no momento'),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='quantidade_litros',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade (Litros)'),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor Total (R$)'),
        ),
        migrations.AlterField(
            model_name='checklistviatura',
            name='odometro',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Odômetro Atual'),
        ),
        migrations.AlterField(
            model_name='despachoviatura',
            name='km_retorno',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Odômetro no Retorno'),
        ),
        migrations.AlterField(
            model_name='despachoviatura',
            name='km_saida',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Odômetro na Saída'),
        ),
        migrations.AlterField(
            model_name='historicalchecklistviatura',
            name='odometro',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Odômetro Atual'),
        ),
        migrations.AlterField(
            model_name='historicalmanutencao',
            name='custo_mao_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Custo Mão de Obra (R$)'),
        ),
        migrations.AlterField(
            model_name='historicalmanutencao',
            name='custo_pecas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Custo Peças (R$)'),
        ),
        migrations.AlterField(
            model_name='historicalmanutencao',
            name='odometro',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Odômetro na Manutenção'),
        ),
        migrations.AlterField(
            model_name='historicalviatura',
            name='ano_fabricacao',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[viaturas.models.validate_ano_fabricacao], verbose_name='Ano de Fabricação'),
        ),
        migrations.AlterField(
            model_name='historicalviatura',
            name='capacidade_tanque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Capacidade do Tanque (L)'),
        ),
        migrations.AlterField(
            model_name='historicalviatura',
            name='odometro_atual',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Km ou Horas(embarcação)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Odômetro/Horímetro Atual'),
        ),
        migrations.AlterField(
            model_name='historicalviatura',
            name='placa',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='placa_invalida', message='Formato de placa inválido. Use ABC-1234 ou ABC1D23 (Mercosul).', regex='^[A-Z]{3}\\s?-?\\s?[0-9][0-9A-Z][0-9]{2}$')], verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='custo_mao_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Custo Mão de Obra (R$)'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='custo_pecas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Custo Peças (R$)'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='odometro',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Odômetro na Manutenção'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[viaturas.models.validate_cnpj], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='pecaviatura',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor Unitário Estimado (R$)'),
        ),
        migrations.AlterField(
            model_name='retiradapecaitem',
            name='quantidade',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='servicomanutencao',
            name='custo_mao_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Custo Mão de Obra (R$)'),
        ),
        migrations.AlterField(
            model_name='servicomanutencao',
            name='custo_pecas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Custo Peças (R$)'),
        ),
        migrations.AlterField(
            model_name='servicomanutencao',
            name='odometro',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Odômetro'),
        ),
        migrations.AlterField(
            model_name='solicitacaobaixaviatura',
            name='quilometragem_baixa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quilometragem/Horímetro na Baixa'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='ano_fabricacao',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[viaturas.models.validate_ano_fabricacao], verbose_name='Ano de Fabricação'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='capacidade_tanque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Capacidade do Tanque (L)'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='odometro_atual',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Km ou Horas(embarcação)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Odômetro/Horímetro Atual'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='placa',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='placa_invalida', message='Formato de placa inválido. Use ABC-1234 ou ABC1D23 (Mercosul).', regex='^[A-Z]{3}\\s?-?\\s?[0-9][0-9A-Z][0-9]{2}$')], verbose_name='Placa'),
        ),
        migrations.AddIndex(
            model_name='abastecimento',
            index=models.Index(fields=['viatura', '-data_abastecimento'], name='idx_abast_viat_data'),
        ),
        migrations.AddIndex(
            model_name='abastecimento',
            index=models.Index(fields=['-data_abastecimento'], name='idx_abast_data'),
        ),
        migrations.AddIndex(
            model_name='abastecimento',
            index=models.Index(fields=['combustivel'], name='idx_abast_combustivel'),
        ),
        migrations.AddIndex(
            model_name='checklistviatura',
            index=models.Index(fields=['viatura', '-data_hora'], name='idx_checklist_viat_data'),
        ),
        migrations.AddIndex(
            model_name='checklistviatura',
            index=models.Index(fields=['tipo'], name='idx_checklist_tipo'),
        ),
        migrations.AddIndex(
            model_name='despachoviatura',
            index=models.Index(fields=['viatura', '-data_saida'], name='idx_despacho_viat_data'),
        ),
        migrations.AddIndex(
            model_name='despachoviatura',
            index=models.Index(fields=['-data_saida'], name='idx_despacho_data_saida'),
        ),
        migrations.AddIndex(
            model_name='despachoviatura',
            index=models.Index(fields=['motorista'], name='idx_despacho_motorista'),
        ),
        migrations.AddIndex(
            model_name='despachoviatura',
            index=models.Index(fields=['viatura', 'data_retorno'], name='idx_despacho_viat_retorno'),
        ),
        migrations.AddIndex(
            model_name='documentoviatura',
            index=models.Index(fields=['viatura', 'tipo'], name='idx_documento_viat_tipo'),
        ),
        migrations.AddIndex(
            model_name='documentoviatura',
            index=models.Index(fields=['data_vencimento'], name='idx_documento_vencimento'),
        ),
        migrations.AddIndex(
            model_name='evidenciamanutencao',
            index=models.Index(fields=['manutencao', 'tipo'], name='idx_evidencia_manut_tipo'),
        ),
        migrations.AddIndex(
            model_name='manutencao',
            index=models.Index(fields=['viatura', 'status'], name='idx_manut_viat_status'),
        ),
        migrations.AddIndex(
            model_name='manutencao',
            index=models.Index(fields=['status'], name='idx_manut_status'),
        ),
        migrations.AddIndex(
            model_name='manutencao',
            index=models.Index(fields=['-data_inicio'], name='idx_manut_data_inicio'),
        ),
        migrations.AddIndex(
            model_name='manutencao',
            index=models.Index(fields=['tipo'], name='idx_manut_tipo'),
        ),
        migrations.AddIndex(
            model_name='manutencao',
            index=models.Index(fields=['data_validade_garantia'], name='idx_manut_validade_garantia'),
        ),
        migrations.AddIndex(
            model_name='manutencao',
            index=models.Index(fields=['oficina_fk'], name='idx_manut_oficina'),
        ),
        migrations.AddIndex(
            model_name='marcaviatura',
            index=models.Index(fields=['ativo', 'nome'], name='idx_marca_ativo_nome'),
        ),
        migrations.AddIndex(
            model_name='modeloviatura',
            index=models.Index(fields=['tipo', 'ativo'], name='idx_modelo_tipo_ativo'),
        ),
        migrations.AddIndex(
            model_name='modeloviatura',
            index=models.Index(fields=['marca', 'nome'], name='idx_modelo_marca_nome'),
        ),
        migrations.AddIndex(
            model_name='oficina',
            index=models.Index(fields=['ativo', 'nome'], name='idx_oficina_ativo_nome'),
        ),
        migrations.AddIndex(
            model_name='pecaviatura',
            index=models.Index(fields=['categoria', 'ativo'], name='idx_peca_categoria_ativo'),
        ),
        migrations.AddIndex(
            model_name='pecaviatura',
            index=models.Index(fields=['ativo', 'nome'], name='idx_peca_ativo_nome'),
        ),
        migrations.AddIndex(
            model_name='pecaviatura',
            index=models.Index(fields=['codigo'], name='idx_peca_codigo'),
        ),
        migrations.AddIndex(
            model_name='planomanutencaopreventiva',
            index=models.Index(fields=['modelo', 'ativo'], name='idx_plano_prev_modelo_ativo'),
        ),
        migrations.AddIndex(
            model_name='registrohistoricomanutencao',
            index=models.Index(fields=['manutencao', '-data_registro'], name='idx_hist_manut_data'),
        ),
        migrations.AddIndex(
            model_name='registrohistoricomanutencao',
            index=models.Index(fields=['tipo'], name='idx_hist_manut_tipo'),
        ),
        migrations.AddIndex(
            model_name='retiradapeca',
            index=models.Index(fields=['viatura', '-data_retirada'], name='idx_retirada_peca_viat_data'),
        ),
        migrations.AddIndex(
            model_name='retiradapeca',
            index=models.Index(fields=['-data_retirada'], name='idx_retirada_peca_data'),
        ),
        migrations.AddIndex(
            model_name='retiradapeca',
            index=models.Index(fields=['policial'], name='idx_retirada_peca_policial'),
        ),
        migrations.AddIndex(
            model_name='retiradapecaitem',
            index=models.Index(fields=['retirada'], name='idx_retirada_item_retirada'),
        ),
        migrations.AddIndex(
            model_name='retiradapecaitem',
            index=models.Index(fields=['peca'], name='idx_retirada_item_peca'),
        ),
        migrations.AddIndex(
            model_name='servicomanutencao',
            index=models.Index(fields=['manutencao', '-data_registro'], name='idx_servico_manut_data'),
        ),
        migrations.AddIndex(
            model_name='solicitacaobaixaviatura',
            index=models.Index(fields=['viatura', 'status'], name='idx_baixa_viat_status'),
        ),
        migrations.AddIndex(
            model_name='solicitacaobaixaviatura',
            index=models.Index(fields=['status'], name='idx_baixa_status'),
        ),
        migrations.AddIndex(
            model_name='solicitacaobaixaviatura',
            index=models.Index(fields=['-data_solicitacao'], name='idx_baixa_data_solic'),
        ),
        migrations.AddIndex(
            model_name='viatura',
            index=models.Index(fields=['status'], name='idx_viatura_status'),
        ),
        migrations.AddIndex(
            model_name='viatura',
            index=models.Index(fields=['localizacao'], name='idx_viatura_localizacao'),
        ),
        migrations.AddIndex(
            model_name='viatura',
            index=models.Index(fields=['placa'], name='idx_viatura_placa'),
        ),
        migrations.AddIndex(
            model_name='viatura',
            index=models.Index(fields=['prefixo'], name='idx_viatura_prefixo'),
        ),
        migrations.AddIndex(
            model_name='viatura',
            index=models.Index(fields=['modelo', 'status'], name='idx_viatura_modelo_status'),
        ),
        migrations.AddConstraint(
            model_name='abastecimento',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_litros__gt', 0)), name='ck_abastecimento_litros_positivo'),
        ),
        migrations.AddConstraint(
            model_name='abastecimento',
            constraint=models.CheckConstraint(condition=models.Q(('odometro__gte', 0)), name='ck_abastecimento_odometro_positivo'),
        ),
        migrations.AddConstraint(
            model_name='abastecimento',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__isnull', True), ('valor_total__gte', 0), _connector='OR'), name='ck_abastecimento_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='checklistviatura',
            constraint=models.CheckConstraint(condition=models.Q(('odometro__gte', 0)), name='ck_checklist_odometro_positivo'),
        ),
        migrations.AddConstraint(
            model_name='despachoviatura',
            constraint=models.CheckConstraint(condition=models.Q(('km_saida__gte', 0)), name='ck_despacho_km_saida_positivo'),
        ),
        migrations.AddConstraint(
            model_name='despachoviatura',
            constraint=models.CheckConstraint(condition=models.Q(('km_retorno__isnull', True), ('km_retorno__gte', 0), _connector='OR'), name='ck_despacho_km_retorno_positivo'),
        ),
        migrations.AddConstraint(
            model_name='despachoviatura',
            constraint=models.CheckConstraint(condition=models.Q(('data_retorno__isnull', True), ('data_retorno__gte', models.F('data_saida')), _connector='OR'), name='ck_despacho_retorno_apos_saida'),
        ),
        migrations.AddConstraint(
            model_name='documentoviatura',
            constraint=models.CheckConstraint(condition=models.Q(('data_emissao__isnull', True), ('data_vencimento__isnull', True), ('data_vencimento__gte', models.F('data_emissao')), _connector='OR'), name='ck_documento_venc_apos_emissao'),
        ),
        migrations.AddConstraint(
            model_name='manutencao',
            constraint=models.CheckConstraint(condition=models.Q(('data_conclusao__isnull', True), ('data_conclusao__gte', models.F('data_inicio')), _connector='OR'), name='ck_manutencao_conclusao_apos_inicio'),
        ),
        migrations.AddConstraint(
            model_name='manutencao',
            constraint=models.CheckConstraint(condition=models.Q(('custo_pecas__gte', 0)), name='ck_manutencao_custo_pecas_positivo'),
        ),
        migrations.AddConstraint(
            model_name='manutencao',
            constraint=models.CheckConstraint(condition=models.Q(('custo_mao_obra__gte', 0)), name='ck_manutencao_custo_mao_obra_positivo'),
        ),
        migrations.AddConstraint(
            model_name='manutencao',
            constraint=models.CheckConstraint(condition=models.Q(('odometro__gte', 0)), name='ck_manutencao_odometro_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pecaviatura',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_estoque__gte', 0)), name='ck_peca_estoque_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='pecaviatura',
            constraint=models.CheckConstraint(condition=models.Q(('limite_minimo__gte', 0)), name='ck_peca_limite_minimo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pecaviatura',
            constraint=models.CheckConstraint(condition=models.Q(('valor_unitario__isnull', True), ('valor_unitario__gte', 0), _connector='OR'), name='ck_peca_valor_unitario_positivo'),
        ),
        migrations.AddConstraint(
            model_name='retiradapecaitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gte', 1)), name='ck_retirada_item_qtd_minima'),
        ),
        migrations.AddConstraint(
            model_name='servicomanutencao',
            constraint=models.CheckConstraint(condition=models.Q(('custo_pecas__gte', 0)), name='ck_servico_manut_custo_pecas_positivo'),
        ),
        migrations.AddConstraint(
            model_name='servicomanutencao',
            constraint=models.CheckConstraint(condition=models.Q(('custo_mao_obra__gte', 0)), name='ck_servico_manut_custo_mao_obra_positivo'),
        ),
        migrations.AddConstraint(
            model_name='solicitacaobaixaviatura',
            constraint=models.CheckConstraint(condition=models.Q(('quilometragem_baixa__isnull', True), ('quilometragem_baixa__gte', 0), _connector='OR'), name='ck_baixa_km_positivo'),
        ),
        migrations.AddConstraint(
            model_name='viatura',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ano_fabricacao__gte', 1950), ('ano_fabricacao__lte', 2028)), ('ano_fabricacao__isnull', True), _connector='OR'), name='ck_viatura_ano_fabricacao_valido'),
        ),
        migrations.AddConstraint(
            model_name='viatura',
            constraint=models.CheckConstraint(condition=models.Q(('capacidade_tanque__gte', 0)), name='ck_viatura_capacidade_tanque_positiva'),
        ),
        migrations.AddConstraint(
            model_name='viatura',
            constraint=models.CheckConstraint(condition=models.Q(('odometro_atual__gte', 0)), name='ck_viatura_odometro_nao_negativo'),
        ),
    ]
