# Generated by Django 5.2.13 on 2026-04-14 17:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0012_movimentacaoestoque_militar_administrativo_and_more'),
        ('policiais', '0002_alter_policial_data_atualizacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria de Patrimônio',
                'verbose_name_plural': 'Categorias de Patrimônio',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='BemPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Bem')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Técnica')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca/Fabricante')),
                ('modelo_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo de Referência')),
                ('valor_unitario_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Unitário Estimado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bens', to='patrimonio.categoriapatrimonio')),
            ],
            options={
                'verbose_name': 'Bem Patrimonial (Catálogo)',
                'verbose_name_plural': 'Bens Patrimoniais (Catálogo)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_patrimonio', models.CharField(help_text='Ex: PM-123456', max_length=50, unique=True, verbose_name='Nº de Patrimônio')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nº de Série')),
                ('estado_conservacao', models.CharField(choices=[('NOVO', 'Novo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('INSERVIVEL', 'Inservível')], default='BOM', max_length=20, verbose_name='Estado de Conservação')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível (Reserva)'), ('EM_USO', 'Em Uso (Cautela)'), ('MANUTENCAO', 'Em Manutenção'), ('BAIXADO', 'Baixado/Inativo'), ('EXTRAVIADO', 'Extraviado/Furto')], default='DISPONIVEL', max_length=20, verbose_name='Status Atual')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Fiscal')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='patrimonio.bempatrimonial')),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.localizacaofisica', verbose_name='Localização')),
                ('responsavel_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_sob_cautela', to='policiais.policial')),
            ],
            options={
                'verbose_name': 'Item Patrimonial (Individual)',
                'verbose_name_plural': 'Itens Patrimoniais (Individuais)',
                'ordering': ['numero_patrimonio'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CAUTELA', 'Cautela (Saída para Policial)'), ('DEVOLUCAO', 'Devolução / Retorno'), ('TRANSFERENCIA', 'Transferência de Local'), ('MANUTENCAO_INICIO', 'Envio para Manutenção'), ('MANUTENCAO_FIM', 'Retorno de Manutenção'), ('BAIXA', 'Baixa Definitiva')], max_length=20, verbose_name='Tipo de Movimentação')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Justificativa/Observações')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='patrimonio.itempatrimonial')),
                ('local_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.localizacaofisica', verbose_name='Local de Destino')),
                ('policial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policiais.policial', verbose_name='Policial Envolvido')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação de Patrimônio',
                'verbose_name_plural': 'Movimentações de Patrimônio',
                'ordering': ['-data_hora'],
            },
        ),
    ]
