# Generated by Django 5.2.17 on 2026-09-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SheetSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('last_pull_at', models.DateTimeField(blank=True, null=True)),
                ('last_push_at', models.DateTimeField(blank=True, null=True)),
                ('last_pull_status', models.CharField(blank=True, max_length=16)),
                ('last_push_status', models.CharField(blank=True, max_length=16)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Estado de sincronização Sheets',
                'verbose_name_plural': 'Estados de sincronização Sheets',
            },
        ),
        migrations.CreateModel(
            name='SheetRowSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=64)),
                ('lookup_key', models.CharField(max_length=64)),
                ('lookup_value', models.CharField(max_length=128)),
                ('row_number', models.IntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Snapshot de linha do Sheets',
                'verbose_name_plural': 'Snapshots de linha do Sheets',
                'unique_together': {('model_name', 'lookup_value')},
            },
        ),
    ]
