# Generated by Django 5.2.17 on 2026-10-06 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('IMPORT_LEGACY', 'Importação Planilha Antiga'), ('SYNC_FULL', 'Sincronização Completa'), ('PULL', 'Pull (Sheets → Django)'), ('PUSH', 'Push (Django → Sheets)'), ('SEED', 'Seed Inicial Planilha Nova')], max_length=32)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Em Andamento'), ('SUCCESS', 'Sucesso Total'), ('PARTIAL_SUCCESS', 'Sucesso Parcial com Avisos'), ('FAILED', 'Falhou'), ('REVERTED', 'Revertido (Rollback)')], default='IN_PROGRESS', max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_records', models.IntegerField(default=0)),
                ('created_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('backup_file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Operação de Sincronização',
                'verbose_name_plural': 'Operações de Sincronização',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncOperationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=64)),
                ('lookup_key', models.CharField(max_length=64)),
                ('lookup_value', models.CharField(max_length=128)),
                ('action', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('SKIP', 'Ignorado'), ('ERROR', 'Erro')], max_length=16)),
                ('status', models.CharField(choices=[('SUCCESS', 'Sucesso'), ('WARNING', 'Aviso'), ('ERROR', 'Erro')], default='SUCCESS', max_length=16)),
                ('sheet_name', models.CharField(blank=True, max_length=128)),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('before_snapshot', models.JSONField(blank=True, null=True)),
                ('after_snapshot', models.JSONField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='integracoes.syncoperation')),
            ],
            options={
                'verbose_name': 'Registro de Operação de Sincronização',
                'verbose_name_plural': 'Registros de Operação de Sincronização',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['operation', 'model_name', 'lookup_value'], name='integracoes_operati_ff9d47_idx')],
            },
        ),
    ]
