# Generated by Django 5.2.14 on 2026-05-27 14:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiais', '0004_lotemunicao'),
        ('policiais', '0002_alter_policial_data_atualizacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucaoMunicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Devolvida')),
                ('estado_devolucao', models.CharField(choices=[('NOVO', 'Novo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('PESSIMO', 'Péssimo')], max_length=20, verbose_name='Estado na Devolução')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora')),
            ],
            options={
                'verbose_name': 'Devolução de Munição',
                'verbose_name_plural': 'Devoluções de Munição',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='LoteMunicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibre', models.CharField(max_length=50, verbose_name='Calibre')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca/Fabricante')),
                ('numero_lote', models.CharField(max_length=100, verbose_name='Número do Lote')),
                ('tipo_municao', models.CharField(choices=[('REAL', 'Real'), ('TREINAMENTO', 'Treinamento'), ('FESTIM', 'Festim'), ('ELASTOMERO', 'Elastômero')], default='REAL', max_length=20, verbose_name='Tipo de Munição')),
                ('data_fabricacao', models.DateField(blank=True, null=True, verbose_name='Data de Fabricação')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('quantidade_inicial', models.PositiveIntegerField(verbose_name='Quantidade Inicial')),
                ('quantidade_atual', models.PositiveIntegerField(verbose_name='Quantidade Atual')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('material', models.ForeignKey(limit_choices_to={'tipo': 'MUNICAO'}, on_delete=django.db.models.deletion.CASCADE, related_name='municao_lotes', to='materiais.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Lote de Munição',
                'verbose_name_plural': 'Lotes de Munição',
                'ordering': ['-data_validade', 'material', 'numero_lote'],
                'unique_together': {('material', 'numero_lote')},
            },
        ),
        migrations.CreateModel(
            name='RegistroDisparoMunicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_disparada', models.PositiveIntegerField(default=0, verbose_name='Quantidade Disparada')),
                ('quantidade_extraviada', models.PositiveIntegerField(default=0, verbose_name='Quantidade Extraviada')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa')),
                ('boletim_ocorrencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='B.O. / Relatório')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('devolucao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_disparo', to='municoes.devolucaomunicao', verbose_name='Devolução')),
            ],
            options={
                'verbose_name': 'Registro de Disparo de Munição',
                'verbose_name_plural': 'Registros de Disparo de Munição',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='RetiradaMunicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('finalidade', models.CharField(max_length=100, verbose_name='Finalidade')),
                ('local_uso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Local de Uso')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiradas', to='municoes.lotemunicao', verbose_name='Lote de Munição')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiradas_municao', to='materiais.material', verbose_name='Material')),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiradas_municao', to='policiais.policial', verbose_name='Policial')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiradas_municao_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Retirada de Munição',
                'verbose_name_plural': 'Retiradas de Munição',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddField(
            model_name='devolucaomunicao',
            name='retirada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='municoes.retiradamunicao', verbose_name='Retirada de Referência'),
        ),
    ]
