# Generated by Django 5.2.14 on 2026-06-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municoes', '0003_fluxo_estojos_e_devolucao_cpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodisparomunicao',
            name='quantidade_estojos_extraviados',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de Estojos Extraviados'),
        ),
        migrations.AddField(
            model_name='retiradamunicao',
            name='tipo_uso',
            field=models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('INSTRUCAO', 'Instrução / Treinamento')], default='OPERACIONAL', max_length=20, verbose_name='Tipo de Uso'),
        ),
        migrations.AlterField(
            model_name='registrodisparomunicao',
            name='quantidade_extraviada',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de Cartuchos Extraviados'),
        ),
        migrations.AlterField(
            model_name='registrodisparomunicao',
            name='sindicancia',
            field=models.CharField(blank=True, help_text='Número da sindicância, procedimento ou referência de apuração da perda/extravio de cartuchos/estojos.', max_length=120, null=True, verbose_name='Sindicância / Apuração'),
        ),
    ]
